### ISSUE TITLE
Only reports good & bad, doesn't report misplaced

### ISSUE THREAD

**Issue by ColinPitrat** [matteli/yesmaster#1]
In MasterMind:
"A colored or black key peg is placed for each code peg from the guess which is correct in both color and position. A white key peg indicates the existence of a correct color code peg placed in the wrong position." [1]

Your program only provides good (correct color at the right place) and bad (this is not the color at this place).

[1] https://en.wikipedia.org/wiki/Mastermind_(board_game)

**Comment by ColinPitrat** [comment]
Example game:

```
$ python3 yesmaster.py play

Test (4 letters among ROGBYAPW):
OBAW
0 good 4 bad

Test (4 letters among ROGBYAPW):
PGRY
0 good 4 bad

Test (4 letters among ROGBYAPW):
YRPG
4 good 0 bad

Bravo 3 attempts
```

**Comment by ColinPitrat** [comment]
Hmm, it seems it's actually an issue only in play mode because code_dict is passed as test_dict:

```
def verify(test, code, test_dict={}, code_dict={}):
```

```
        good, bad = verify(test, code, code_dict)
```

This is called correctly in auto:

```
            good, bad = verify(test=test, code=code, code_dict=code_dict)
```

**Comment by matteli** [comment]
The word "bad" is not correct but it means misplaced.
So your exemple game is correct.

**Comment by ColinPitrat** [comment]
It's not correct, the first attempt has four "real bad" and the second attempt has four "misplaced". PR #2 fixes the issue

**Comment by matteli** [comment]
No sorry, i don't look for the first attempt. You're right, i don't update the call of verify in the play mode.
