### ISSUE TITLE
Algos should be in an object

### ISSUE THREAD

**Issue by ColinPitrat** [matteli/yesmaster#3]
Currently, an algo is just 3 functions in a file.
This should be encapsulated into an object (which would remove the need for the init function).

The reason is that any algo that requires some data has to rely on global data so that it's shared between the functions.

Global variables are bad for multiple reasons but mainly, in my case, it's easy to forget to add the global variable declaration to a function modifying it, with weird failure modes. This could also cause problems if you run multiple instance of a same algo (could make sense with some future evolution). Finally this would make it easier to make algos with parameters.

**Comment by matteli** [comment]
You're right.

**Comment by matteli** [comment]
I make change for this issue in algo_object branch.
@ColinPitrat you need to adapt your algo (one_step_ahead) if you want

**Comment by ColinPitrat** [comment]
You'll need to update the readme :)

**Comment by matteli** [comment]
It's done in the algo_object branch.
"2 functions are mandatory in a class name Algo :
- get(self) : executed for choosing the code. Must return a 4 letters string with letters among ROGBYAPW
- report(self, test, good, bad) : executed with 3 arguments (test : the code that you pushed with get, good : the number of good colors at good place, bad : the number of good colors at wrong place). Return nothing.
"
I forgot something ?

**Comment by ColinPitrat** [comment]
Ah yeah, I didn't notice it was on a branch :-)

Trying it out:
```
$ python3 yesmaster.py -a compatible_8in2 auto
Traceback (most recent call last):
  File "/home/cpitrat/Perso/yesmaster/yesmaster/yesmaster.py", line 131, in <module>
    main(what=args.what, algo=args.algo, loop=args.loop)
  File "/home/cpitrat/Perso/yesmaster/yesmaster/yesmaster.py", line 110, in main
    auto(algo, loop)
  File "/home/cpitrat/Perso/yesmaster/yesmaster/yesmaster.py", line 54, in auto
    test = algo.get()
  File "/home/cpitrat/Perso/yesmaster/yesmaster/algo/compatible_8in2.py", line 38, in get
    test = random_code_4_colors(except_colors=test1)
UnboundLocalError: local variable 'test1' referenced before assignment
```

**Comment by matteli** [comment]
There is a bug in this algo. It's fixed now. Always in algo_object branch

**Comment by matteli** [comment]
Fixed and merged
